apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  selector:
    matchLabels:
      app: userprofile
  replicas: 2
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryfgf3387.azurecr.io/userprofile:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

        env:
          - name: SQL_SERVER
            value: "sqlserverfgf3387.database.windows.net"
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: userprofilesecret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: userprofilesecret
                key: SQL_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: userprofilesecret
type: Opaque
stringData:
    SQL_USER: "sqladminfGf3387"
    SQL_PASSWORD: "nD7kh8Vr1"
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  selector:
    app: userprofile
  ports:
  - port: 80
    targetPort: 80

