apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
spec:
  selector:
    matchLabels:
      app: tripviewer
  replicas: 2
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryfgf3387.azurecr.io/tripviewer:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

        env:
          - name: TRIPS_API_ENDPOINT
            value: "http://trips"
          - name: USERPROFILE_API_ENDPOINT
            value: "http://userprofile"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  type: LoadBalancer
  selector:
    app: tripviewer
  ports:
  - port: 80
    targetPort: 80
---


