kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-users-full-access
  namespace: web
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-users-full-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-users-full-access
subjects:
- kind: Group
  namespace: web
  name: e6ae5f37-e913-4151-80a4-2809b7a018bf
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-readonly-access
  namespace: web
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-readonly-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-user-readonly-access
subjects:
- kind: Group
  namespace: web
  name: 606a2dd8-1a9e-425f-b916-6c02d5ff972d
