apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryfgf3387.azurecr.io/poi:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

        env:
          - name: SQL_SERVER
            value: "sqlserverfgf3387.database.windows.net"
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SQL_PASSWORD
---

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
    SQL_USER: "sqladminfGf3387"
    SQL_PASSWORD: "nD7kh8Vr1"
---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  selector:
    app: poi
  ports:
  - port: 80
    targetPort: 80

