apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava
spec:
  selector:
    matchLabels:
      app: userjava
  replicas: 2
  template:
    metadata:
      labels:
        app: userjava
    spec:
      containers:
      - name: userjava
        image: registryfgf3387.azurecr.io/userjava:1.0
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 80

        env:
          - name: SQL_SERVER
            value: "sqlserverfgf3387.database.windows.net"
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: userjavasecret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: userjavasecret
                key: SQL_PASSWORD
---

apiVersion: v1
kind: Secret
metadata:
  name: userjavasecret
type: Opaque
stringData:
    SQL_USER: "sqladminfGf3387"
    SQL_PASSWORD: "nD7kh8Vr1"
---
apiVersion: v1
kind: Service
metadata:
  name: userjava
spec:
  selector:
    app: userjava
  ports:
  - port: 80
    targetPort: 80

